---
#UPDATE - UPGRADE
- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Upgrading all packages (CentOS)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"
   
#INSTALL COMMON PACKAGES 
- name: Instala paquetes common
  packages: 
    name: "{{ packages }}"
  vars:
    packages:
      - ccze
      - iftop
      - iotop
      - iptables-persistent
      - language-pack-es
      - lm-sensors
      - lshw
      - multitail
      - nano
      - ncdu
      - netcat
      - netcat-openbsd
      - nmap
      - nmon
      - pigz
      - powertop
      - preload
      - psensor
      - pv
      - python-packaging
      - ruby-full
      - screen
      - siege
      - stress
      - tcpdump
      - telnetd
      - unrar
      - unzip
      - vim
      - vim-common
      - vim-snippets
      - virtualenv
      - whois
      - zip
      - zlib1g-dev
    state: present
  #register: common-packages-installation
  tags: common
