---
#UPDATE - UPGRADE
- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

# - name: Upgrading all packages (CentOS)
#   yum:
#     name: '*'
#     state: latest
#   when: ansible_os_family == "RedHat"
   
#    #INSTALL i386 COMMON PACKAGES 
#- name: Instala paquetes common i386  
#  apt:
#    name: "{{ packages }}"
#    update_cache: "{{add_i386.changed}}"
#  vars:
#    packages:
#      - libgl1-mesa-dri:i386
#      - libgl1-mesa-glx:i386
#      - libasound2-plugins:i386
#      - wine-stable:i386
#      - wine32-development

#INSTALL COMMON PACKAGES 
- name: Instala paquetes common
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - acl
      - apt-transport-https
      - apt-xapian-index
      - aptitude
      # - arc-theme
      - arj
      - atop
      - autoconf
      - automake
      # - awscli
      # - balena-etcher-electron
      - bc
      - bison
      # - boot-repair
      # - brasero-cdrkit
      - build-essential
      - ca-certificates
      # - catfish
      - ccze
      - checkinstall
      # - chromium-browser
      # - chromium-browser-l10n
      # - chromium-codecs-ffmpeg
      - clang
      - cmake
      - cmake-curses-gui
      - collectd
      # - compiz
      # - compiz-plugins-extra
      # - compizconfig-settings-manager
      - curl
      # - dbus
      # - dconf-editor
      - default-jdk
      - default-jre
      # - dia
      - dirmngr
      - dnsmasq
      - docker
      - docker-ce
      - docker-compose
      # - dropbox
      - ebtables
      - fdupes
      # - figlet
      # - file-roller
      # - filezilla
      # - filezilla-common
      # - filezilla-theme-papirus
      - flatpak
      # - fonts-noto
      # - forticlient
      - fpc
      # - freeglut3
      - g++
      - gcc
      # - gdebi
      # - gimp
      # - gir1.2-clutter-1.0
      # - gir1.2-gtop-2.0
      - git
      - git-flow
      - git-ftp
      - git-lfs
      - git-svn
      # - gnome-shell-extensions
      # - gnome-software-plugin-flatpak
      # - gnome-tweak-tool
      - gnupg2
      - golang-go
      # - google-cloud-sdk
      # - google-cloud-sdk-bigtable-emulator
      # - google-cloud-sdk-cbt
      # - google-cloud-sdk-cloud-build-local
      # - google-cloud-sdk-datalab
      # - google-cloud-sdk-app-engine-go
      # - google-cloud-sdk-app-engine-java
      # - google-cloud-sdk-app-engine-python
      # - google-cloud-sdk-app-engine-python-extras
      # - google-cloud-sdk-pubsub-emulator
      # - google-cloud-sdk-bigtable-emulator
      # - google-cloud-sdk-datastore-emulator
      # - google-cloud-sdk-firestore-emulator
      # - google-chrome-stable
      # - gpick
      # - graphviz
      # - grub-customizer
      # - gufw
      # - hardinfo
      - hddtemp
      - htop
      - iftop
      # - intel-microcode
      - iotop
      - iptables-persistent
      - iptstate
      - jq
      # - k3b
      # - kdeconnect
      # - kubectl
      # - libavformat-dev
      # - libdvd-pkg
      # - libegl1-mesa
      # - libelf-dev
      # - libffi-dev
      # - libfile-tee-perl
      # - libfreetype6-dev
      # - libgdbm-dev
      # - libguestfs-perl
      # - libjack-dev
      # - libjack0
      # - libjansson-dev
      # - liblua5.3-dev
      # - libmagic-dev
      # - libncurses5-dev
      # - libopencv-highgui-dev
      # - libportmidi-dev
      # - libreadline-dev
      # - libswscale-dev
      # #- libsdl2-image-dev
      # - libsqlite3-dev
      # - libssl-dev
      # - libstdc++5
      # - libstdc++6
      # - libsvn-java
      # - libtool
      # - libvirt-bin
      # - libvirt-dev
      # - libxml-writer-perl
      # - libxml2-dev
      # - libxslt-dev
      # - libyaml-dev
      - linux-generic
      - linux-headers-generic
      - lldpd
      - lm-sensors
      - lsb-release
      - lshw
      # - lxd
      # - lxd-client
      # - lutris
      - mailutils
      - make
      # - meld
      # - module-assistant
      - moreutils
      - mpack
      - multipath-tools
      - multitail
      # - mysql-workbench-community
      - nano
      - ncdu
      - netcat
      - netcat-openbsd
      # - network-manager-openvpn
      # - network-manager-openvpn-gnome
      - nfs-common
      - nfs-kernel-server
      - nmap
      - nmon
      - nodejs
      - ntp
      - ntpdate
      # - numix-blue-gtk-theme
      # - numix-gtk-theme
      # - numix-icon-theme
      # - numix-icon-theme-circle
      # - nvidia-cuda-dev
      # - nvidia-cuda-toolkit
      # - openfortivpn
      - openssh-client
      - openssh-server
      # - openvpn
      - p7zip-full
      - p7zip-rar
      # - papirus-icon-theme
      # - pepperflashplugin-nonfree
      # - pgadmin3
      - pigz
      - pkg-config
      # - plank
      # - playonlinux
      # - portaudio19-dev
      - postfix
      - powertop
      - preload
      - psensor
      # - pulseaudio-equalizer
      - putty-tools
      - pv
      - python
      - python3-pip
      - python-setuptools
      # - qemu
      # - qemu-kvm
      # - quodlibet
      - rar
      - rbenv
      # - redshift
      # - redshift-gtk
      # - remmina
      # - rdesktop
      # - rdfind
      # - rtl8812au-dkms
      - ruby-dev
      - ruby-full
      - screen
      - sharutils
      # - shutter
      - siege
      # - skypeforlinux
      - smartmontools
      - snapd
      - snmp
      - snmp-mibs-downloader
      - snmpd
      - software-properties-common
      # - soundconverter
      # - spotify-client
      # - ssh-askpass
      # - steam
      - stress
      # - sublime-merge
      # - sublime-text
      - subversion
      - sudo
      - swaks
      - synaptic
      - syncthing
      # - synergy -- not available yet
      - sysstat
      - tcpdump
      - telnetd
      # - terminator
      # - tinyca
      # - tmux
      # - tor
      # - torbrowser-launcher
      # - ttf-bitstream-vera
      # - ttf-dejavu
      # - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - unace
      - unixodbc-dev
      - unrar
      - unzip
      - uuid-runtime
      - vim
      - vim-common
      # - vim-gtk
      # - vim-gui-common
      - vim-snippets
      # - virt-manager
      # - virt-viewer
      # - virtinst
      # - virtualbox-6.1
      # - vlc
      - whois
      #- wine1.8
      #- wine32-development
      # - xclip
      - xinetd
      # - xserver-xorg
      # - xserver-xorg-input-all
      # - xserver-xorg-video-all
      - yarn
      - zip
      - zlib1g-dev
      - zsh
      # - chrome-gnome-shell
      # - screenfetch
      # - calibre
      - python-packaging
      - language-pack-es
      # - gnome-tweaks
      # - wine
      # - winetricks
      # - laptop-mode-tools
      # - timeshift
      # - libglib2.0-dev-bin
      # - vlc-plugin-bittorrent
      # Lutris Vulkan
      # - nvidia-driver-440 
      # - libnvidia-gl-440 
      # - libnvidia-gl-440:i386
      # - libvulkan1
      # - libvulkan1:i386
      # - libgl1-mesa-dri:i386
      # - mesa-vulkan-drivers
      # - mesa-vulkan-drivers:i386
      # - variety
      # - shotwell
      # - vinagre
      - virtualenv
      # - stellarium
      # - celestia
      # - synergy
      #- winehq-stable
    state: present
  #register: common-packages-installation
  tags: common

# # Snap
# - name: Install snaps
#   snap:
#     name:
#       - k9s
#       - postman
#       - insomnia
#       - telegram-desktop
#       # - discord
#       - keepassxc
#       # - rambox
#       # - wickrpro
#       # - wickrme
#       - lxd
#       - vault
#       - signal-desktop
#       - zoom-client

# - name: Install snaps classic
#   snap:
#     name:
#       - slack
#       # - eclipse
#       # - atom
#       # - phpstorm
#       - code
#       - skype
#     classic: yes

# Flatpak
# - name: Add the Gnome flatpak remote to the system installation
#   flatpak_remote:
#     name: gnome
#     state: present
#     flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

