---
#CREATE SSH KEY
- name: Create a 4096-bit SSH key for user root
  user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa

- name : list users to create ssh keys
  shell: "getent passwd | awk -F: '$3 > 999 {print $1}'"
  register: users_ssh

- debug:
    var: users_ssh
    verbosity: 2

- name: Create a 4096-bit SSH key for current users
  user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
  with_items: "{{ users_ssh.stdout_lines }}"